### ISSUE TITLE
Support for configuring trust store

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jersey-client#15]
Often we have to read from HTTPS connections that have self-signed certificates (or certificates that are signed by a proper authority, that is unfortunately not known to Java). In this case we need to explicitly tell our clients about those certificates by providing a "trust store". Let's add local trust store to jerseyclient config:

``` yaml
jerseyclient:
  trustStore: classpath:ts.jks
  trustStorePassword: changeit # make this default
```
