### ISSUE TITLE
Support for authentication filters

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jersey-client#2]
Let's support transparent configuration-driven authentication options for the client, starting with BASIC. Sample YAML:

```
jerseyclient:
  auth:
    name1:
       type: basic
       username: u1
       password: p1
```

`HttpClientFactory` can be extended to get an authenticated client referencing named auth:

``` java
Client newAuthenticatedClient(String authName)
```
