### ISSUE TITLE
HttpTargets : Configuring named targets

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jersey-client#26]
Suggested feature would allow to configure individual URL targets. E.g.:

```yaml
jerseyclient:
   compression: true
   auth:
    compression: false
     a1: 
        type: basic
   trustStores:
      ts1:
         location: classpath:embedded_truststore.jks
   targets:
     t1:
       url: "https://bootique.io"
       compression: true # this overrides parent compression settings
       trustStore: ts1 # this is a reference to the named trustStore
       auth: a1 # this is a reference to the named auth
```

```java
// This object is injectable
interface HttpTargets {
   WebTarget newTarget(String name);
}
```

This is trying to address a number of practical problems:
1. The users really don't care about the Client object. They want `WebTarget` with some base URL in most cases. 
2. Keeping the base URL outside of the client configuration requires the apps to write their own factories with URL configuration.
3. ~~Current singleton configuration does not allow to override trust store per client, which is often problematic (e.g. some targets have self-signed certs and require a custom trust store, others are using proper certificates and require the default JVM trust store).~~ (scratching this. It will be addressed per #28)

_TODO: we should test registering Features for named targets... and that different features for different targets do not interfere with each other._
