### ISSUE TITLE
Named truststores,  Client builder

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jersey-client#28]
The apps occasionally need more than one truststore. Or a typical situation when a client for one endpoint needs a custom trust store (because the server is using self-signed certificates), and all others are fine with the default JVM truststore. So going to replace (with deprecation) the current singleton truststore with a new config tree:

```yaml
jerseyclient:
   trustStore:
     ts1:
       location: "classpath:ts1"
       password: "changeit" # "changeit"  is the default of course and can be omitted
    ts2:
      location: ....
```
The use of it will require adding builder method to `HttpClientFactory`:

```java
clientFactory.newClientBuilder().auth("a1").trustStore("ts1").build();
```
