### ISSUE TITLE
Support for OAuth 2 authenticator

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jersey-client#4]
In addition to the BASIC auth supported already, let's add an OAuth 2 athenticator that would support "[client credentials](https://tools.ietf.org/html/rfc6749#section-4.4)" auth flow , returning a Client with cached Bearer token that will be used for API requests. Possible config structure:

```
jerseyclient:
  auth:
    twitter:
      type: oauth2
      tokenUrl: https://api.twitter.com/oauth2/token
      username: xyz
      password: 123
```

This should be enough to access APIs like Twitter, Github, Google, etc. out of the box with no custom security code.
