### ISSUE TITLE
RuntimeException in WebTarget that use authentication with type "oauth"

### ISSUE THREAD

**Issue by vvertinskiy** [bootique/bootique-jersey-client#42]
Use case:
1. YML-config - WebTarget with authentication; authentication with type "oauth2"
```
jerseyclient:
  auth:
    myauth:
      type: oauth2
      tokenUrl: "..."
      username: "..."
      password: "..."
  targets:
    mytarget:
      auth: "apptoken"
```
2. As result, WebTarget with client request filter OAuth2TokenAuthenticator is registered 
3. When WebTarget is used, filter OAuth2TokenAuthenticator tries to get token value with help of POST request to "tokenUrl" with basic authorization header
4. If username/password is invalid then POST request in p.3 returns response with 401 status.
5. But filter OAuth2TokenAuthenticator translates this response to RuntimeException:
Class **_io.bootique.jersey.client.auth.OAuth2TokenDAO_**:

```
protected OAuth2Token readToken(Response response) {
       if (response.getStatus() != Response.Status.OK.getStatusCode()) {
           String json = response.readEntity(String.class);
           String message = String.format(“Error reading token: %s ... %s”, response.getStatus(), json);
           throw new RuntimeException(message);
       }
….
}
```

Maybe is it needed to translate status 401 (and other Http statuses) of POST request in p.3 to corresponded ClientErrorException, not to RuntimeException
