### ISSUE TITLE
"apiKeyHeader" and "apiKeyParameter" authenticators

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jersey-client#44]
We currently support "oauth2" and "basic" auth out of the box for clients. Here is another common type of authentication - [API key](https://swagger.io/docs/specification/authentication/api-keys/). While to the best of my knowledge it is not formally specified anywhere, I've seen a number of popular services using it. According to that Swagger link above there may be three common varieties: 

* Appending API Key as URL parameter
* Passing it as a header
* Passing it in a cookie

We'll implement two types of authenticators - "apiKeyParameter"  and "apiKeyHeader" with the following configuration (Cookie is a kind of a header; also yet to see a service that uses cookies for this) : 

```yml
jerseyclient:
  auth:
    myservice1:
      type: "apiKeyHeader" 
      # Header name. If missing, "X-Api-Key" is assumed
      name: "X-MyService-Api-Key" 
      # API Key value. Required
      key: "abc12345"
    myservice2:
      type: "apiKeyParameter" 
      # Query param name. If missing, "api_key" is assumed
      name: "my_key" 
      # API Key value. Required
      key: "abc12345"
```
